services:
  - type: web
    name: yenha-blog
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
