services:
  - type: web
    name: yenha-blog
    env: docker
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: yenha2026
    healthCheckPath: /api/posts
    autoDeploy: true
